### ISSUE TITLE
valgrind invalid read in contract()

### ISSUE THREAD

**Issue by trevor-vincent** [smorita/mptensor#6]
This minimal example

```
#include <mpi.h>
#include <mptensor/mptensor.hpp>

int main(int argc, char **argv) {
  using namespace mptensor;
  typedef Tensor<lapack::Matrix, double> ptensor;
  ptensor A(Shape(2,2,2));
  for (int i = 0; i < A.local_size(); i++) A[i] = i;
  A = contract(A, Axes(0), Axes(1));
}
```

Produces an  "Invalid read of size 8" message when I run "valgrind ./a.out". It appears to be harmless, but clutters up valgrind output if using the mptensor library.

**Comment by smorita** [comment]
Thank you for creating a clear example. I confirmed the problem and push a commit fixed it.

**Comment by trevor-vincent** [comment]
Awesome, thank you!
